title: Sana Azmeh 
author: GitHub User
email: sazmeh@andtechllc.com
description: > # this means to ignore newlines until "baseurl:"
  Sana is a web designer and developer. She makes websites to be nice, user friendly and fast.
# social links
twitter_username: sanaazmeh # DO NOT include the @ character, or else the build will fail!
github_username:  sazmeh # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
